# Generated by Django 4.1.7 on 2023-04-01 05:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=1000)),
                ('subject', models.CharField(max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to='records/anouncements')),
                ('date_announced', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['date_announced', 'sender'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment', models.CharField(max_length=20)),
                ('details', models.TextField(blank=True, max_length=500, null=True)),
                ('date', models.DateTimeField()),
                ('venue', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done')], default='Pending', max_length=20)),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'db_table': 'appointments',
                'ordering': ['date', 'status'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('time_in', models.TimeField(blank=True, null=True)),
                ('break_time', models.TimeField(blank=True, null=True)),
                ('time_out', models.TimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendance',
                'ordering': ['date', 'time_in', 'staff'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ExportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('export_format', models.CharField(choices=[('xlsx', 'Xlsx'), ('xls', 'Xls'), ('csv', 'Csv'), ('json', 'Json')], default='xlsx', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('Annual', 'Annual'), ('Unpaid', 'Unpaid'), ('Maternity', 'Maternity'), ('paternity', 'Paternity'), ('Compersory', 'Compersory')], default='Annual', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('date_applied', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Completed', 'Completed'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
            ],
            options={
                'verbose_name': 'Leave Application',
                'verbose_name_plural': 'Leave Applications',
                'ordering': ['start_date', 'end_date', 'staff', 'status'],
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('food_allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('house_allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('health_allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('transport_allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('other_allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('benefits', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('overtime', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bonus', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('transaction_id', models.CharField(blank=True, max_length=30, null=True)),
                ('month', models.CharField(blank=True, max_length=30, null=True)),
                ('pay_date', models.DateField()),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Held', 'Held'), ('Suspended', 'Suspended')], default='Paid', max_length=10)),
            ],
            options={
                'verbose_name': 'Payroll',
                'verbose_name_plural': 'Payrolls',
                'ordering': ['pay_date', 'staff'],
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField()),
                ('score', models.CharField(max_length=10)),
                ('comment', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='StaffPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StaffShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(max_length=20)),
                ('time', models.TimeField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_in', models.TimeField()),
                ('time_out', models.TimeField()),
            ],
            options={
                'verbose_name': 'Timetable',
                'verbose_name_plural': 'Timetables',
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('venue', models.CharField(max_length=50)),
                ('completed', models.BooleanField(default=False)),
                ('data', models.JSONField()),
            ],
            options={
                'verbose_name': 'Training',
                'verbose_name_plural': 'Trainings',
                'ordering': ['date', 'completed'],
            },
        ),
    ]
