# Generated by Django 4.1.7 on 2023-04-01 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=30, null=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='settings/logo')),
                ('use_name', models.BooleanField(default=True)),
                ('company_email', models.CharField(blank=True, max_length=50, null=True)),
                ('company_address', models.CharField(blank=True, max_length=50, null=True)),
                ('company_zip', models.CharField(blank=True, max_length=50, null=True)),
                ('company_mobile_number', models.IntegerField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
