# Generated by Django 4.1.7 on 2023-04-01 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='reference_number',
            field=models.CharField(default=2787248554, max_length=10, unique=True),
        ),
    ]
