# Generated by Django 4.1.7 on 2023-04-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_alter_document_reference_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='reference_number',
            field=models.CharField(default=956630689, max_length=10, unique=True),
        ),
    ]
