# Generated by Django 4.1.7 on 2023-04-03 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0005_alter_document_reference_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='reference_number',
            field=models.CharField(default=904162236, max_length=10, unique=True),
        ),
    ]
