# Generated by Django 4.1.7 on 2023-04-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0006_alter_document_reference_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='reference_number',
            field=models.CharField(default=374876743, max_length=10, unique=True),
        ),
    ]
